apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pim-backend-db-url
  namespace: pim
spec:
  encryptedData:
    DATABASE_URL: AgBnaxopRWAwwaMSmYUkSPvmkWsWnX+Nr/LVrLghRvs4AkfyjtkktHRUJIkGJnuC4Ut1xc/9gfy4TrnXRO8+kJTKnxJeYwZrYwIR3bc48U2mfqKTe69qaB4Jiex8oMFpkkQ21Kc18CBSVIlVefEUWmAKoFbxmeS6cX5qqckpDNCjoMY9Gl5SfNRthhVj181x5qLbcP06Bu/BG1Nwv0FK6M89rgk3FDuECw/saxjlYpEiUHU0nXQi+9YKDdyhscZDSTWBK6xCUXWmiu63aS3+6gsQG/hRxcXlqj1tCqUsOlsHDq4+OBATfsXquAmhfDMS8/wamwdUboMOGIISCeMIewfqJKsy39gtYLw6JrYAhJkSWXDJvld/rSLiAc0olLFrf+ELblbqOy6GVqGJPS/pAURgc0jFp8u1ykDl7lKWd/GBKgY/DbTxN+8HkTF8OcKwjKPiH10JjQv28R8N0LHfef5pDGroukkzOS63i1PTBpNlW4isLgSek4wvru0Osct26ZniXd8oEHWkundTuEPbBFGAiGqXeyX7zMIJXqSK5DjvmPNZcP+aKec5JRLcWvU9oQ61KV0XBIESeG68OPmT1P+1D7x+auQW9BFmNa3/65o4vIPKqvCx6unJ4yV6CgsxajzwdWPS6Z+KHujbLeZJmMPSnwPf0HTR7vgpweSVgP6Rzg5JEwgDxepUTVXNzVS2alrN3KgqanW/t3+jK/EHmYUgbRgyh5Sw82FM5VIbySWgP4o+8adLHWYVZJ/vbHYgFoQnScgVp/fAM9KJtIQqdPuixxyXPCa368JYbSO9ik6heu4llFcgSWKN
  template:
    metadata:
      name: pim-backend-db-url
      namespace: pim
    type: Opaque