apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pim-backend-db-url
  namespace: pim
spec:
  encryptedData:
    DATABASE_URL: PLACEHOLDER_ENCRYPTED_VALUE
  template:
    metadata:
      name: pim-backend-db-url
      namespace: pim
    type: Opaque